name: chess
dependencies:
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_0
- python=3.5.2=0
- readline=6.2=2
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- theano=0.8.2=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - keras==1.1.2
  - python-chess==0.15.4
  - pyyaml==3.12

